create table category(
cat_id int not null generated by default as identity primary key,
cat_name varchar(15) not null
);

alter table category add constraint uniquectm_const unique (cat_name);

insert into category(cat_name) values('Romance'), ('Thriller'), ('Sci-fi'), ('Fantasy'), ('Non Fiction'), ('History');

create type avail as enum('yes','no');

create table book(
isbn varchar(15) not null primary key,
title varchar(30) not null,
author varchar (50) not null,
description varchar(120),
category_id int not null,
pub_date date not null,
publisher varchar(30),
availability avail default 'yes',
foreign key(category_id) references category(cat_id));


insert into book values ('123456', 'Scala', 'Martin Odersky', 'Come and have fun with Scala', 5, '01-01-2018', 'OReilly', 'yes');

insert into book values ('4327843', '1984', 'George Orwell', 'Scary book light years ahead of its time', 3, '01-01-2019', 'Penguin', 'yes');

insert into book values ('3524635', 'Outlander', 'Diana Gabaldon', 'Amazing story, romance through times', 1, '10-07-1991', 'Delacorte Books', 'no');

insert into book values ('2333647', 'The Witcher', 'Andrzej Sapkowski', 'Follow a strange guy fighting creatures', 4, '08-16-1986', 'SuperNowa', 'yes');
